# Stage 1: Build
FROM node:23 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .


# Stage 2: Run development server
EXPOSE 5173
CMD ["npm", "run", "dev"]



#RUN npm run build

# Stage 2: Serve
#FROM nginx:alpine

#COPY --from=builder /app/dist /usr/share/nginx/html

#EXPOSE 80