version: "3.8"

services:
  frontend: 
    build: ./frontend 
    ports:
      - "8080:80"
    networks:
      - webnet

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
