FROM python:3.11-slim

RUN apt-get update && apt-get install -y build-essential make

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

WORKDIR /app/src/interpreter
RUN make
RUN chmod +x ./main.exe

WORKDIR /app

ENV FLASK_APP=src/app.py
EXPOSE 5001

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]