FROM python:3.11-slim

RUN apt-get update && apt-get install -y build-essential make gcc

WORKDIR /app
COPY . .
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN ls -l
WORKDIR /app/src/interpreter

RUN gcc -o main main.c lexer.c parser.c interpreter.c -I.

# Check if 'main' was created
RUN ls -l /app/src/interpreter/main

# Make 'main' executable
RUN chmod +x ./main

WORKDIR /app

ENV FLASK_APP=src/app.py
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1
EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]