version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - ../backend:/app
    environment:
      - FLASK_ENV=development  
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app 
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  nginx:
    build: ../nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
