version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev  # or Dockerfile.prod
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - ../backend:/app  # Mounts the backend code to the container
    environment:
      - FLASK_ENV=development  # Example for Flask, enable development mode for auto-reload

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev  # or Dockerfile.prod
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app  # Mounts the frontend code to the container
      - /app/node_modules
    environment:
      - NODE_ENV=development  # Example for Svelte, enable development mode for hot reload

  nginx:
    build: ../nginx
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
