version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app
    environment:
      - FLASK_ENV=production 
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    restart: unless-stopped

  nginx:
    build: ../nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
